# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reai_toolkit/app/components/forms/about/about_panel_qt5.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutPanel(object):
    def setupUi(self, AboutPanel):
        AboutPanel.setObjectName("AboutPanel")
        AboutPanel.resize(600, 800)
        AboutPanel.setMinimumSize(QtCore.QSize(600, 800))
        AboutPanel.setMaximumSize(QtCore.QSize(600, 800))
        AboutPanel.setStyleSheet(
            "\n"
            "    QGroupBox{font-weight:600;margin-top:8px;}\n"
            "    QGroupBox::title{subcontrol-origin: margin; left: 6px; padding:2px 4px;}\n"
            "    QLineEdit{border:1px solid #3c3f44;border-radius:6px;padding:6px;}\n"
            "    QLineEdit:focus{border-color:#5865f2;}\n"
            "    QPushButton{border:1px solid #3c3f44;border-radius:8px;padding:6px 12px;}\n"
            "    QPushButton:hover{border-color:#5865f2;}\n"
            "    #okButton{background:rgb(35,144,236);color:white;border:0;border-radius:8px;padding:6px 12px;}\n"
            "    #cancelButton{background:rgb(153,12,25);color:white;border:0;border-radius:8px;padding:6px 12px;}\n"
            "    #btnDiscord{background:rgb(83, 54, 228); color:white;border:0;border-radius:8px;padding:6px 12px;}\n"
            "    #btnEmail{background:rgb(218, 73, 59); color:white;border:0;border-radius:8px;padding:6px 12px;}\n"
            "   "
        )
        self.rootLayout = QtWidgets.QVBoxLayout(AboutPanel)
        self.rootLayout.setContentsMargins(12, 12, 12, 12)
        self.rootLayout.setSpacing(10)
        self.rootLayout.setObjectName("rootLayout")
        self.header = QtWidgets.QFrame(AboutPanel)
        self.header.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.header.setObjectName("header")
        self.headerLayout = QtWidgets.QHBoxLayout(self.header)
        self.headerLayout.setSpacing(12)
        self.headerLayout.setObjectName("headerLayout")
        self.logoArea = QtWidgets.QLabel(self.header)
        self.logoArea.setMinimumSize(QtCore.QSize(72, 72))
        self.logoArea.setMaximumSize(QtCore.QSize(96, 96))
        self.logoArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.logoArea.setText("")
        self.logoArea.setPixmap(
            QtGui.QPixmap(
                "reai_toolkit/app/components/forms/about/../../resources/reveng_ai_logo.jpg"
            )
        )
        self.logoArea.setScaledContents(True)
        self.logoArea.setObjectName("logoArea")
        self.headerLayout.addWidget(self.logoArea)
        self.titleLayout = QtWidgets.QVBoxLayout()
        self.titleLayout.setObjectName("titleLayout")
        self.titleLabel = QtWidgets.QLabel(self.header)
        self.titleLabel.setStyleSheet("font-size:18px;font-weight:600;")
        self.titleLabel.setObjectName("titleLabel")
        self.titleLayout.addWidget(self.titleLabel)
        self.subtitleLabel = QtWidgets.QLabel(self.header)
        self.subtitleLabel.setAutoFillBackground(False)
        self.subtitleLabel.setStyleSheet("color: palette(text);")
        self.subtitleLabel.setObjectName("subtitleLabel")
        self.titleLayout.addWidget(self.subtitleLabel)
        self.headerLayout.addLayout(self.titleLayout)
        self.rootLayout.addWidget(self.header)
        self.groupEndpoints = QtWidgets.QGroupBox(AboutPanel)
        self.groupEndpoints.setMinimumSize(QtCore.QSize(0, 150))
        self.groupEndpoints.setObjectName("groupEndpoints")
        self.errorLayout = QtWidgets.QVBoxLayout(self.groupEndpoints)
        self.errorLayout.setSpacing(6)
        self.errorLayout.setObjectName("errorLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupEndpoints)
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setObjectName("textBrowser")
        self.errorLayout.addWidget(self.textBrowser)
        self.supportGroupBox = QtWidgets.QGroupBox(self.groupEndpoints)
        self.supportGroupBox.setMinimumSize(QtCore.QSize(0, 60))
        self.supportGroupBox.setMaximumSize(QtCore.QSize(16777215, 60))
        self.supportGroupBox.setObjectName("supportGroupBox")
        self.supportLayout = QtWidgets.QHBoxLayout(self.supportGroupBox)
        self.supportLayout.setSpacing(8)
        self.supportLayout.setObjectName("supportLayout")
        spacerItem = QtWidgets.QSpacerItem(
            20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.supportLayout.addItem(spacerItem)
        self.btnDiscord = QtWidgets.QPushButton(self.supportGroupBox)
        self.btnDiscord.setObjectName("btnDiscord")
        self.supportLayout.addWidget(self.btnDiscord)
        self.btnEmail = QtWidgets.QPushButton(self.supportGroupBox)
        self.btnEmail.setObjectName("btnEmail")
        self.supportLayout.addWidget(self.btnEmail)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.supportLayout.addItem(spacerItem1)
        self.errorLayout.addWidget(self.supportGroupBox)
        self.rootLayout.addWidget(self.groupEndpoints)
        self.buttonsRow = QtWidgets.QHBoxLayout()
        self.buttonsRow.setObjectName("buttonsRow")
        spacerItem2 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.buttonsRow.addItem(spacerItem2)
        self.okButton = QtWidgets.QPushButton(AboutPanel)
        self.okButton.setMinimumSize(QtCore.QSize(80, 25))
        self.okButton.setMaximumSize(QtCore.QSize(80, 25))
        self.okButton.setObjectName("okButton")
        self.buttonsRow.addWidget(self.okButton)
        spacerItem3 = QtWidgets.QSpacerItem(
            0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.buttonsRow.addItem(spacerItem3)
        self.rootLayout.addLayout(self.buttonsRow)

        self.retranslateUi(AboutPanel)
        QtCore.QMetaObject.connectSlotsByName(AboutPanel)

    def retranslateUi(self, AboutPanel):
        _translate = QtCore.QCoreApplication.translate
        AboutPanel.setWindowTitle(_translate("AboutPanel", "RevEng.AI — About"))
        self.titleLabel.setText(_translate("AboutPanel", "Help"))
        self.subtitleLabel.setText(
            _translate("AboutPanel", "Documentation for the options in the menu bar")
        )
        self.groupEndpoints.setTitle(_translate("AboutPanel", "RevEng.AI"))
        self.textBrowser.setHtml(
            _translate(
                "AboutPanel",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'.AppleSystemUIFont'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
                '<h2 style=" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><a name="welcome-to-reveng-ai"></a><span style=" font-size:x-large; font-weight:600;">W</span><span style=" font-size:x-large; font-weight:600;">elcome to RevEng.AI</span></h2>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">This panel provides an overview of features available from the RevEng.AI menu.</p>\n'
                '<h2 style=" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><a name="quick-start"></a><span style=" font-size:x-large; font-weight:600;">Q</span><span style=" font-size:x-large; font-weight:600;">uick Start</span></h2>\n'
                '<ol style="margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;"><li style="" style=" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Authenticate via: RevEng.AI → Configure</li>\n'
                '<li style="" style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Analyse the current binary with RevEng.AI via: RevEng.AI → Analysis → Create New</li>\n'
                '<li style="" style=" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Use other RevEng.AI Features to improve your analysis!</li></ol>\n'
                '<h2 style=" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><a name="full-feature-list"></a><span style=" font-size:x-large; font-weight:600;">F</span><span style=" font-size:x-large; font-weight:600;">ull Feature List</span></h2>\n'
                '<h3 style=" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><a name="analysis"></a><span style=" font-size:large; font-weight:600;">A</span><span style=" font-size:large; font-weight:600;">nalysis</span></h3>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">To use the RevEng.AI platform we need to run an analysis on the binary you are currently working with in our portal. Use this section to create and manage this analysis.<br />This section is only available after the plugin has been configured.</p>\n'
                '<ul style="margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;"><li style="" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-weight:600;">Create new</span><br />Creates a new analysis in the RevEng.AI portal and attaches to it.</li>\n'
                '<li style="" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-weight:600;">Attach to existing</span><br />List matching portal analyses and allow selecting one to attach to.</li>\n'
                '<li style="" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-weight:600;">Detach</span><br />Detach from portal analysis.</li>\n'
                '<li style="" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-weight:600;">Check status</span><br />Checks the status of a running analysis.</li></ul>\n'
                '<h3 style=" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><a name="auto-unstrip"></a><span style=" font-size:large; font-weight:600;">A</span><span style=" font-size:large; font-weight:600;">uto Unstrip</span></h3>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">This option will run an automatic unstrip process on the current binary using the RevEng.AI API.<br />The process uses a high confidence threshold to rename functions and variables.<br />This option is only available when an analysis is attached and has completed processing.</p>\n'
                '<h3 style=" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><a name="function-matching"></a><span style=" font-size:large; font-weight:600;">F</span><span style=" font-size:large; font-weight:600;">unction Matching</span></h3>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Run a function match against the RevEng.AI API to identify functions that were not renamed during the automatic unstrip process.<br />This option is configurable to run against specific target binaries by using specific filters.<br />This option is only available when an analysis is attached and has completed processing.</p>\n'
                '<h3 style=" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><a name="configure"></a><span style=" font-size:large; font-weight:600;">C</span><span style=" font-size:large; font-weight:600;">onfigure</span></h3>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Configure the API endpoint and API key.</p>\n'
                '<h3 style=" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><a name="help"></a><span style=" font-size:large; font-weight:600;">H</span><span style=" font-size:large; font-weight:600;">elp</span></h3>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Display this page.</p>\n'
                '<h3 style=" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><a name="about"></a><span style=" font-size:large; font-weight:600;">A</span><span style=" font-size:large; font-weight:600;">bout</span></h3>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Display plugin version.</p>\n'
                "<hr />\n"
                '<h3 style=" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><a name="secondary-click-on-a-function"></a><span style=" font-size:large; font-weight:600;">S</span><span style=" font-size:large; font-weight:600;">econdary click on a function</span></h3>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Documentation for the options available on secondary click on a specific function.</p>\n'
                '<ul style="margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;"><li style="" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-weight:600;">AI Decompilation</span><br />Decompile function using the RevEng.AI proprietary decompiler.</li>\n'
                '<li style="" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-weight:600;">Match function</span><br />Run a match against the RevEng.AI API for this function.<br />Only available for non-debug functions. </li></ul></body></html>',
            )
        )
        self.supportGroupBox.setTitle(_translate("AboutPanel", "Support/Contact"))
        self.btnDiscord.setToolTip(_translate("AboutPanel", "Join our Discord"))
        self.btnDiscord.setText(_translate("AboutPanel", "Discord"))
        self.btnEmail.setToolTip(_translate("AboutPanel", "Contact us via email"))
        self.btnEmail.setText(_translate("AboutPanel", "Email"))
        self.okButton.setText(_translate("AboutPanel", "Dismiss"))
