# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reai_toolkit/app/components/forms/auth/auth_panel_qt5.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AuthPanel(object):
    def setupUi(self, AuthPanel):
        AuthPanel.setObjectName("AuthPanel")
        AuthPanel.resize(420, 360)
        AuthPanel.setMinimumSize(QtCore.QSize(420, 360))
        AuthPanel.setMaximumSize(QtCore.QSize(420, 360))
        AuthPanel.setAutoFillBackground(False)
        AuthPanel.setStyleSheet(
            "\n"
            "    QGroupBox{font-weight:600;margin-top:8px;}\n"
            "    QGroupBox::title{subcontrol-origin: margin; left: 6px; padding:2px 4px;}\n"
            "    QLineEdit{border:1px solid #3c3f44;border-radius:6px;padding:6px;}\n"
            "    QLineEdit:focus{border-color:#5865f2;}\n"
            "    QPushButton{border:1px solid #3c3f44;border-radius:8px;padding:6px 12px;}\n"
            "    QPushButton:hover{border-color:#5865f2;}\n"
            "    #okButton {\n"
            "      background:rgb(35, 144, 236); color:white; border:0; border-radius:8px; padding:6px 12px;\n"
            "    }\n"
            "    #cancelButton {\n"
            "      background:rgb(153, 12, 25); color:white; border:0; border-radius:8px; padding:6px 12px;\n"
            "    }\n"
            "   "
        )
        self.rootLayout = QtWidgets.QVBoxLayout(AuthPanel)
        self.rootLayout.setContentsMargins(12, 12, 12, 12)
        self.rootLayout.setSpacing(10)
        self.rootLayout.setObjectName("rootLayout")
        self.header = QtWidgets.QFrame(AuthPanel)
        self.header.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.header.setObjectName("header")
        self.headerLayout = QtWidgets.QHBoxLayout(self.header)
        self.headerLayout.setSpacing(12)
        self.headerLayout.setObjectName("headerLayout")
        self.logoArea = QtWidgets.QLabel(self.header)
        self.logoArea.setMinimumSize(QtCore.QSize(72, 72))
        self.logoArea.setMaximumSize(QtCore.QSize(96, 96))
        self.logoArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.logoArea.setText("")
        self.logoArea.setPixmap(
            QtGui.QPixmap(
                "reai_toolkit/app/components/forms/auth/../../resources/reveng_ai_logo.jpg"
            )
        )
        self.logoArea.setScaledContents(True)
        self.logoArea.setObjectName("logoArea")
        self.headerLayout.addWidget(self.logoArea)
        self.titleLayout = QtWidgets.QVBoxLayout()
        self.titleLayout.setObjectName("titleLayout")
        self.titleLabel = QtWidgets.QLabel(self.header)
        self.titleLabel.setStyleSheet("font-size:18px;font-weight:600;")
        self.titleLabel.setObjectName("titleLabel")
        self.titleLayout.addWidget(self.titleLabel)
        self.subtitleLabel = QtWidgets.QLabel(self.header)
        self.subtitleLabel.setAutoFillBackground(False)
        self.subtitleLabel.setStyleSheet("color: palette(text);")
        self.subtitleLabel.setObjectName("subtitleLabel")
        self.titleLayout.addWidget(self.subtitleLabel)
        self.headerLayout.addLayout(self.titleLayout)
        self.rootLayout.addWidget(self.header)
        self.groupEndpoints = QtWidgets.QGroupBox(AuthPanel)
        self.groupEndpoints.setObjectName("groupEndpoints")
        self.formLayout = QtWidgets.QFormLayout(self.groupEndpoints)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight)
        self.formLayout.setObjectName("formLayout")
        self.labelApiUrl = QtWidgets.QLabel(self.groupEndpoints)
        self.labelApiUrl.setObjectName("labelApiUrl")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelApiUrl)
        self.apiUrlEdit = QtWidgets.QLineEdit(self.groupEndpoints)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apiUrlEdit.sizePolicy().hasHeightForWidth())
        self.apiUrlEdit.setSizePolicy(sizePolicy)
        self.apiUrlEdit.setMinimumSize(QtCore.QSize(296, 32))
        self.apiUrlEdit.setMaximumSize(QtCore.QSize(296, 32))
        self.apiUrlEdit.setObjectName("apiUrlEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.apiUrlEdit)
        self.labelPortalUrl = QtWidgets.QLabel(self.groupEndpoints)
        self.labelPortalUrl.setObjectName("labelPortalUrl")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.labelPortalUrl
        )
        self.portalUrlEdit = QtWidgets.QLineEdit(self.groupEndpoints)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.portalUrlEdit.sizePolicy().hasHeightForWidth()
        )
        self.portalUrlEdit.setSizePolicy(sizePolicy)
        self.portalUrlEdit.setMinimumSize(QtCore.QSize(296, 32))
        self.portalUrlEdit.setMaximumSize(QtCore.QSize(296, 32))
        self.portalUrlEdit.setObjectName("portalUrlEdit")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.portalUrlEdit
        )
        self.labelApiKey = QtWidgets.QLabel(self.groupEndpoints)
        self.labelApiKey.setObjectName("labelApiKey")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelApiKey)
        self.apiKeyEdit = QtWidgets.QLineEdit(self.groupEndpoints)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apiKeyEdit.sizePolicy().hasHeightForWidth())
        self.apiKeyEdit.setSizePolicy(sizePolicy)
        self.apiKeyEdit.setMinimumSize(QtCore.QSize(296, 32))
        self.apiKeyEdit.setMaximumSize(QtCore.QSize(296, 32))
        self.apiKeyEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.apiKeyEdit.setObjectName("apiKeyEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.apiKeyEdit)
        self.rootLayout.addWidget(self.groupEndpoints)
        self.linkRow = QtWidgets.QHBoxLayout()
        self.linkRow.setObjectName("linkRow")
        spacerItem = QtWidgets.QSpacerItem(
            0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.linkRow.addItem(spacerItem)
        self.getKeyLink = QtWidgets.QLabel(AuthPanel)
        self.getKeyLink.setStyleSheet("color: palette(highlight);")
        self.getKeyLink.setOpenExternalLinks(True)
        self.getKeyLink.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.getKeyLink.setObjectName("getKeyLink")
        self.linkRow.addWidget(self.getKeyLink)
        self.rootLayout.addLayout(self.linkRow)
        self.buttonsRow = QtWidgets.QHBoxLayout()
        self.buttonsRow.setObjectName("buttonsRow")
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.buttonsRow.addItem(spacerItem1)
        self.cancelButton = QtWidgets.QPushButton(AuthPanel)
        self.cancelButton.setObjectName("cancelButton")
        self.buttonsRow.addWidget(self.cancelButton)
        self.okButton = QtWidgets.QPushButton(AuthPanel)
        self.okButton.setObjectName("okButton")
        self.buttonsRow.addWidget(self.okButton)
        spacerItem2 = QtWidgets.QSpacerItem(
            0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.buttonsRow.addItem(spacerItem2)
        self.rootLayout.addLayout(self.buttonsRow)
        self.labelApiUrl.setBuddy(self.apiUrlEdit)
        self.labelPortalUrl.setBuddy(self.portalUrlEdit)
        self.labelApiKey.setBuddy(self.apiKeyEdit)

        self.retranslateUi(AuthPanel)
        QtCore.QMetaObject.connectSlotsByName(AuthPanel)

    def retranslateUi(self, AuthPanel):
        _translate = QtCore.QCoreApplication.translate
        AuthPanel.setWindowTitle(_translate("AuthPanel", "RevEng.AI — Connection"))
        self.titleLabel.setText(_translate("AuthPanel", "RevEng.AI — Configuration"))
        self.subtitleLabel.setText(
            _translate("AuthPanel", "Configure service endpoints and credentials")
        )
        self.groupEndpoints.setTitle(_translate("AuthPanel", "Endpoints"))
        self.labelApiUrl.setText(_translate("AuthPanel", "API URL"))
        self.apiUrlEdit.setText(_translate("AuthPanel", "https://api.reveng.ai"))
        self.apiUrlEdit.setPlaceholderText(
            _translate("AuthPanel", "https://api.reveng.ai")
        )
        self.labelPortalUrl.setText(_translate("AuthPanel", "Portal URL"))
        self.portalUrlEdit.setText(_translate("AuthPanel", "https://portal.reveng.ai"))
        self.portalUrlEdit.setPlaceholderText(
            _translate("AuthPanel", "https://portal.reveng.ai")
        )
        self.labelApiKey.setText(_translate("AuthPanel", "API Key"))
        self.apiKeyEdit.setPlaceholderText(
            _translate("AuthPanel", "Paste your API key…")
        )
        self.getKeyLink.setToolTip(
            _translate(
                "AuthPanel", "Open the RevEng.AI portal to create or view your API key"
            )
        )
        self.getKeyLink.setText(
            _translate("AuthPanel", '<a href="#">Get an API key</a>')
        )
        self.cancelButton.setText(_translate("AuthPanel", "Cancel"))
        self.okButton.setText(_translate("AuthPanel", "OK"))
