# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reai_toolkit/app/components/forms/auto_unstrip/auto_unstrip_panel_qt5.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AutoUnstripPanel(object):
    def setupUi(self, AutoUnstripPanel):
        AutoUnstripPanel.setObjectName("AutoUnstripPanel")
        AutoUnstripPanel.resize(600, 400)
        AutoUnstripPanel.setMinimumSize(QtCore.QSize(600, 400))
        AutoUnstripPanel.setMaximumSize(QtCore.QSize(600, 400))
        AutoUnstripPanel.setAutoFillBackground(False)
        AutoUnstripPanel.setStyleSheet(
            "\n"
            "    QGroupBox{font-weight:600;margin-top:8px;}\n"
            "    QGroupBox::title{subcontrol-origin: margin; left: 6px; padding:2px 4px;}\n"
            "    QLineEdit{border:1px solid #3c3f44;border-radius:6px;padding:6px;}\n"
            "    QLineEdit:focus{border-color:#5865f2;}\n"
            "    QPushButton{border:1px solid #3c3f44;border-radius:8px;padding:6px 12px;}\n"
            "    QPushButton:hover{border-color:#5865f2;}\n"
            "    #okButton { background:rgb(35,144,236); color:white; border:0; border-radius:8px; padding:6px 12px; }\n"
            "    #cancelButton { background:rgb(153,12,25); color:white; border:0; border-radius:8px; padding:6px 12px; }\n"
            "   "
        )
        self.rootLayout = QtWidgets.QVBoxLayout(AutoUnstripPanel)
        self.rootLayout.setContentsMargins(12, 12, 12, 12)
        self.rootLayout.setSpacing(10)
        self.rootLayout.setObjectName("rootLayout")
        self.header = QtWidgets.QFrame(AutoUnstripPanel)
        self.header.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.header.setObjectName("header")
        self.headerLayout = QtWidgets.QHBoxLayout(self.header)
        self.headerLayout.setSpacing(12)
        self.headerLayout.setObjectName("headerLayout")
        self.logoArea = QtWidgets.QLabel(self.header)
        self.logoArea.setMinimumSize(QtCore.QSize(72, 72))
        self.logoArea.setMaximumSize(QtCore.QSize(96, 96))
        self.logoArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.logoArea.setText("")
        self.logoArea.setPixmap(
            QtGui.QPixmap(
                "reai_toolkit/app/components/forms/auto_unstrip/../../resources/reveng_ai_logo.jpg"
            )
        )
        self.logoArea.setScaledContents(True)
        self.logoArea.setObjectName("logoArea")
        self.headerLayout.addWidget(self.logoArea)
        self.titleLayout = QtWidgets.QVBoxLayout()
        self.titleLayout.setObjectName("titleLayout")
        self.titleLabel = QtWidgets.QLabel(self.header)
        self.titleLabel.setStyleSheet("font-size:18px;font-weight:600;")
        self.titleLabel.setObjectName("titleLabel")
        self.titleLayout.addWidget(self.titleLabel)
        self.subtitleLabel = QtWidgets.QLabel(self.header)
        self.subtitleLabel.setAutoFillBackground(False)
        self.subtitleLabel.setStyleSheet("color: palette(placeholderText);")
        self.subtitleLabel.setObjectName("subtitleLabel")
        self.titleLayout.addWidget(self.subtitleLabel)
        self.headerLayout.addLayout(self.titleLayout)
        self.rootLayout.addWidget(self.header)
        self.groupRenames = QtWidgets.QGroupBox(AutoUnstripPanel)
        self.groupRenames.setObjectName("groupRenames")
        self.groupLayout = QtWidgets.QVBoxLayout(self.groupRenames)
        self.groupLayout.setSpacing(8)
        self.groupLayout.setObjectName("groupLayout")
        self.tableRenames = QtWidgets.QTableWidget(self.groupRenames)
        self.tableRenames.setMinimumSize(QtCore.QSize(550, 0))
        self.tableRenames.setMaximumSize(QtCore.QSize(550, 16777215))
        self.tableRenames.setEditTriggers(
            QtWidgets.QAbstractItemView.DoubleClicked
            | QtWidgets.QAbstractItemView.EditKeyPressed
        )
        self.tableRenames.setAlternatingRowColors(True)
        self.tableRenames.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableRenames.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableRenames.setWordWrap(True)
        self.tableRenames.setRowCount(0)
        self.tableRenames.setColumnCount(4)
        self.tableRenames.setObjectName("tableRenames")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableRenames.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableRenames.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableRenames.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableRenames.setHorizontalHeaderItem(3, item)
        self.tableRenames.horizontalHeader().setVisible(True)
        self.tableRenames.horizontalHeader().setCascadingSectionResizes(True)
        self.tableRenames.horizontalHeader().setDefaultSectionSize(110)
        self.tableRenames.horizontalHeader().setMinimumSectionSize(10)
        self.tableRenames.horizontalHeader().setStretchLastSection(True)
        self.tableRenames.verticalHeader().setVisible(False)
        self.groupLayout.addWidget(self.tableRenames)
        self.rootLayout.addWidget(self.groupRenames)
        self.buttonsRow = QtWidgets.QHBoxLayout()
        self.buttonsRow.setObjectName("buttonsRow")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.buttonsRow.addItem(spacerItem)
        self.okButton = QtWidgets.QPushButton(AutoUnstripPanel)
        self.okButton.setDefault(True)
        self.okButton.setObjectName("okButton")
        self.buttonsRow.addWidget(self.okButton)
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.buttonsRow.addItem(spacerItem1)
        self.rootLayout.addLayout(self.buttonsRow)

        self.retranslateUi(AutoUnstripPanel)
        QtCore.QMetaObject.connectSlotsByName(AutoUnstripPanel)

    def retranslateUi(self, AutoUnstripPanel):
        _translate = QtCore.QCoreApplication.translate
        AutoUnstripPanel.setWindowTitle(
            _translate("AutoUnstripPanel", "RevEng.AI — Auto Unstrip")
        )
        self.titleLabel.setText(
            _translate("AutoUnstripPanel", "RevEng.AI — Auto Unstrip")
        )
        self.subtitleLabel.setText(
            _translate("AutoUnstripPanel", "Automatically rename unknown functions.")
        )
        self.groupRenames.setTitle(_translate("AutoUnstripPanel", "Applied Names"))
        self.tableRenames.setSortingEnabled(True)
        item = self.tableRenames.horizontalHeaderItem(0)
        item.setText(_translate("AutoUnstripPanel", "Select"))
        item = self.tableRenames.horizontalHeaderItem(1)
        item.setText(_translate("AutoUnstripPanel", "Virtual Address"))
        item = self.tableRenames.horizontalHeaderItem(2)
        item.setText(_translate("AutoUnstripPanel", "Current Name"))
        item = self.tableRenames.horizontalHeaderItem(3)
        item.setText(_translate("AutoUnstripPanel", "Suggested Name"))
        self.okButton.setText(_translate("AutoUnstripPanel", "OK"))
