# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reai_toolkit/app/components/forms/ai_decomp/ai_decomp_panel_qt5.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AiDecompPanel(object):
    def setupUi(self, AiDecompPanel):
        AiDecompPanel.setObjectName("AiDecompPanel")
        AiDecompPanel.resize(900, 800)
        AiDecompPanel.setMinimumSize(QtCore.QSize(900, 800))
        AiDecompPanel.setMaximumSize(QtCore.QSize(900, 800))
        AiDecompPanel.setStyleSheet(
            "\n"
            "    QGroupBox{font-weight:600;margin-top:8px;}\n"
            "    QGroupBox::title{subcontrol-origin: margin; left: 6px; padding:2px 4px;}\n"
            "    QLineEdit{border:1px solid #3c3f44;border-radius:6px;padding:6px;}\n"
            "    QLineEdit:focus{border-color:#5865f2;}\n"
            "    QPushButton{border:1px solid #3c3f44;border-radius:8px;padding:6px 12px;}\n"
            "    QPushButton:hover{border-color:#5865f2;}\n"
            "    #okButton{background:rgb(35,144,236);color:white;border:0;border-radius:8px;padding:6px 12px;}\n"
            "    #cancelButton{background:rgb(153,12,25);color:white;border:0;border-radius:8px;padding:6px 12px;}\n"
            "\n"
            "    /* thumbs styling (requires SVGs that use currentColor) */\n"
            "    QPushButton#buttonThumbsUp { color: palette(text); }\n"
            "    QPushButton#buttonThumbsUp:checked { color: #16a34a; } /* green */\n"
            "\n"
            "    QPushButton#buttonThumbsDown { color: palette(text); }\n"
            "    QPushButton#buttonThumbsDown:checked { color: #dc2626; } /* red */\n"
            "   "
        )
        self.rootLayout = QtWidgets.QVBoxLayout(AiDecompPanel)
        self.rootLayout.setContentsMargins(12, 12, 12, 12)
        self.rootLayout.setSpacing(10)
        self.rootLayout.setObjectName("rootLayout")
        self.header = QtWidgets.QFrame(AiDecompPanel)
        self.header.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.header.setObjectName("header")
        self.headerLayout = QtWidgets.QHBoxLayout(self.header)
        self.headerLayout.setSpacing(12)
        self.headerLayout.setObjectName("headerLayout")
        self.logoArea = QtWidgets.QLabel(self.header)
        self.logoArea.setMinimumSize(QtCore.QSize(72, 72))
        self.logoArea.setMaximumSize(QtCore.QSize(96, 96))
        self.logoArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.logoArea.setText("")
        self.logoArea.setPixmap(
            QtGui.QPixmap(
                "reai_toolkit/app/components/forms/ai_decomp/../../resources/reveng_ai_logo.jpg"
            )
        )
        self.logoArea.setScaledContents(True)
        self.logoArea.setObjectName("logoArea")
        self.headerLayout.addWidget(self.logoArea)
        self.titleLayout = QtWidgets.QVBoxLayout()
        self.titleLayout.setObjectName("titleLayout")
        self.titleLabel = QtWidgets.QLabel(self.header)
        self.titleLabel.setStyleSheet("font-size:18px;font-weight:600;")
        self.titleLabel.setObjectName("titleLabel")
        self.titleLayout.addWidget(self.titleLabel)
        self.subtitleLabel = QtWidgets.QLabel(self.header)
        self.subtitleLabel.setAutoFillBackground(False)
        self.subtitleLabel.setStyleSheet("color: palette(text);")
        self.subtitleLabel.setObjectName("subtitleLabel")
        self.titleLayout.addWidget(self.subtitleLabel)
        self.headerLayout.addLayout(self.titleLayout)
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.headerLayout.addItem(spacerItem)
        self.ratingLayout = QtWidgets.QHBoxLayout()
        self.ratingLayout.setObjectName("ratingLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.header)
        self.label.setStyleSheet("color: palette(text);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.buttonThumbsDown = QtWidgets.QPushButton(self.header)
        self.buttonThumbsDown.setMinimumSize(QtCore.QSize(60, 0))
        self.buttonThumbsDown.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(
                "reai_toolkit/app/components/forms/ai_decomp/../../resources/thumb_down.svg"
            ),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.buttonThumbsDown.setIcon(icon)
        self.buttonThumbsDown.setIconSize(QtCore.QSize(24, 24))
        self.buttonThumbsDown.setCheckable(True)
        self.buttonThumbsDown.setObjectName("buttonThumbsDown")
        self.horizontalLayout_2.addWidget(self.buttonThumbsDown)
        self.buttonThumbsUp = QtWidgets.QPushButton(self.header)
        self.buttonThumbsUp.setMinimumSize(QtCore.QSize(60, 0))
        self.buttonThumbsUp.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap(
                "reai_toolkit/app/components/forms/ai_decomp/../../resources/thumb_up.svg"
            ),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.buttonThumbsUp.setIcon(icon1)
        self.buttonThumbsUp.setIconSize(QtCore.QSize(24, 24))
        self.buttonThumbsUp.setCheckable(True)
        self.buttonThumbsUp.setObjectName("buttonThumbsUp")
        self.horizontalLayout_2.addWidget(self.buttonThumbsUp)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.ratingLayout.addLayout(self.verticalLayout)
        self.headerLayout.addLayout(self.ratingLayout)
        self.rootLayout.addWidget(self.header)
        self.groupEndpoints = QtWidgets.QGroupBox(AiDecompPanel)
        self.groupEndpoints.setMinimumSize(QtCore.QSize(0, 150))
        self.groupEndpoints.setObjectName("groupEndpoints")
        self.errorLayout = QtWidgets.QVBoxLayout(self.groupEndpoints)
        self.errorLayout.setSpacing(6)
        self.errorLayout.setObjectName("errorLayout")
        self.codeEditor = QtWidgets.QPlainTextEdit(self.groupEndpoints)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.codeEditor.sizePolicy().hasHeightForWidth())
        self.codeEditor.setSizePolicy(sizePolicy)
        self.codeEditor.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.codeEditor.setReadOnly(True)
        self.codeEditor.setObjectName("codeEditor")
        self.errorLayout.addWidget(self.codeEditor)
        self.rootLayout.addWidget(self.groupEndpoints)
        self.linkRow = QtWidgets.QHBoxLayout()
        self.linkRow.setObjectName("linkRow")
        self.rootLayout.addLayout(self.linkRow)

        self.retranslateUi(AiDecompPanel)
        QtCore.QMetaObject.connectSlotsByName(AiDecompPanel)

    def retranslateUi(self, AiDecompPanel):
        _translate = QtCore.QCoreApplication.translate
        AiDecompPanel.setWindowTitle(
            _translate("AiDecompPanel", "RevEng.AI — Ai Decomp")
        )
        self.titleLabel.setText(_translate("AiDecompPanel", "RevEng.AI — AI Decomp"))
        self.subtitleLabel.setText(_translate("AiDecompPanel", "AI Decompilation"))
        self.label.setText(_translate("AiDecompPanel", "Rate the AI-Decompilation"))
        self.groupEndpoints.setTitle(_translate("AiDecompPanel", "Log"))
