# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reai_toolkit/app/components/forms/error/error_panel_qt5.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AuthPanel(object):
    def setupUi(self, AuthPanel):
        AuthPanel.setObjectName("AuthPanel")
        AuthPanel.resize(420, 360)
        AuthPanel.setMinimumSize(QtCore.QSize(420, 360))
        AuthPanel.setMaximumSize(QtCore.QSize(420, 360))
        AuthPanel.setStyleSheet(
            "\n"
            "    QGroupBox{font-weight:600;margin-top:8px;}\n"
            "    QGroupBox::title{subcontrol-origin: margin; left: 6px; padding:2px 4px;}\n"
            "    QLineEdit{border:1px solid #3c3f44;border-radius:6px;padding:6px;}\n"
            "    QLineEdit:focus{border-color:#5865f2;}\n"
            "    QPushButton{border:1px solid #3c3f44;border-radius:8px;padding:6px 12px;}\n"
            "    QPushButton:hover{border-color:#5865f2;}\n"
            "    #okButton{background:rgb(35,144,236);color:white;border:0;border-radius:8px;padding:6px 12px;}\n"
            "    #cancelButton{background:rgb(153,12,25);color:white;border:0;border-radius:8px;padding:6px 12px;}\n"
            "   "
        )
        self.rootLayout = QtWidgets.QVBoxLayout(AuthPanel)
        self.rootLayout.setContentsMargins(12, 12, 12, 12)
        self.rootLayout.setSpacing(10)
        self.rootLayout.setObjectName("rootLayout")
        self.header = QtWidgets.QFrame(AuthPanel)
        self.header.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.header.setObjectName("header")
        self.headerLayout = QtWidgets.QHBoxLayout(self.header)
        self.headerLayout.setSpacing(12)
        self.headerLayout.setObjectName("headerLayout")
        self.logoArea = QtWidgets.QLabel(self.header)
        self.logoArea.setMinimumSize(QtCore.QSize(72, 72))
        self.logoArea.setMaximumSize(QtCore.QSize(96, 96))
        self.logoArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.logoArea.setText("")
        self.logoArea.setPixmap(
            QtGui.QPixmap(
                "reai_toolkit/app/components/forms/error/../../resources/reveng_ai_logo.jpg"
            )
        )
        self.logoArea.setScaledContents(True)
        self.logoArea.setObjectName("logoArea")
        self.headerLayout.addWidget(self.logoArea)
        self.titleLayout = QtWidgets.QVBoxLayout()
        self.titleLayout.setObjectName("titleLayout")
        self.titleLabel = QtWidgets.QLabel(self.header)
        self.titleLabel.setStyleSheet("font-size:18px;font-weight:600;")
        self.titleLabel.setObjectName("titleLabel")
        self.titleLayout.addWidget(self.titleLabel)
        self.subtitleLabel = QtWidgets.QLabel(self.header)
        self.subtitleLabel.setAutoFillBackground(False)
        self.subtitleLabel.setStyleSheet("color: palette(text);")
        self.subtitleLabel.setObjectName("subtitleLabel")
        self.titleLayout.addWidget(self.subtitleLabel)
        self.headerLayout.addLayout(self.titleLayout)
        self.rootLayout.addWidget(self.header)
        self.groupEndpoints = QtWidgets.QGroupBox(AuthPanel)
        self.groupEndpoints.setMinimumSize(QtCore.QSize(0, 150))
        self.groupEndpoints.setObjectName("groupEndpoints")
        self.errorLayout = QtWidgets.QVBoxLayout(self.groupEndpoints)
        self.errorLayout.setSpacing(6)
        self.errorLayout.setObjectName("errorLayout")
        self.errorMessage = QtWidgets.QLabel(self.groupEndpoints)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.errorMessage.sizePolicy().hasHeightForWidth())
        self.errorMessage.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setItalic(True)
        self.errorMessage.setFont(font)
        self.errorMessage.setAutoFillBackground(False)
        self.errorMessage.setStyleSheet(
            "padding:6px;border:1px solid #3c3f44;border-radius:6px;"
        )
        self.errorMessage.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.errorMessage.setLineWidth(10)
        self.errorMessage.setTextFormat(QtCore.Qt.MarkdownText)
        self.errorMessage.setScaledContents(False)
        self.errorMessage.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop
        )
        self.errorMessage.setWordWrap(True)
        self.errorMessage.setIndent(5)
        self.errorMessage.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.errorMessage.setObjectName("errorMessage")
        self.errorLayout.addWidget(self.errorMessage)
        self.rootLayout.addWidget(self.groupEndpoints)
        self.linkRow = QtWidgets.QHBoxLayout()
        self.linkRow.setObjectName("linkRow")
        spacerItem = QtWidgets.QSpacerItem(
            0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.linkRow.addItem(spacerItem)
        self.rootLayout.addLayout(self.linkRow)
        self.buttonsRow = QtWidgets.QHBoxLayout()
        self.buttonsRow.setObjectName("buttonsRow")
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.buttonsRow.addItem(spacerItem1)
        self.okButton = QtWidgets.QPushButton(AuthPanel)
        self.okButton.setMinimumSize(QtCore.QSize(60, 30))
        self.okButton.setMaximumSize(QtCore.QSize(60, 30))
        self.okButton.setObjectName("okButton")
        self.buttonsRow.addWidget(self.okButton)
        spacerItem2 = QtWidgets.QSpacerItem(
            0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.buttonsRow.addItem(spacerItem2)
        self.rootLayout.addLayout(self.buttonsRow)

        self.retranslateUi(AuthPanel)
        QtCore.QMetaObject.connectSlotsByName(AuthPanel)

    def retranslateUi(self, AuthPanel):
        _translate = QtCore.QCoreApplication.translate
        AuthPanel.setWindowTitle(_translate("AuthPanel", "RevEng.AI — Connection"))
        self.titleLabel.setText(_translate("AuthPanel", "RevEng.AI — Log"))
        self.subtitleLabel.setText(_translate("AuthPanel", "Service Logs & Messages"))
        self.groupEndpoints.setTitle(_translate("AuthPanel", "Error"))
        self.errorMessage.setText(_translate("AuthPanel", "```0: Error Message```"))
        self.okButton.setText(_translate("AuthPanel", "OK"))
