# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reai_toolkit/app/components/forms/existing_analysis/existing_analysis_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExistingAnalysesPanel(object):
    def setupUi(self, ExistingAnalysesPanel):
        ExistingAnalysesPanel.setObjectName("ExistingAnalysesPanel")
        ExistingAnalysesPanel.resize(800, 800)
        ExistingAnalysesPanel.setMinimumSize(QtCore.QSize(800, 800))
        ExistingAnalysesPanel.setMaximumSize(QtCore.QSize(800, 800))
        ExistingAnalysesPanel.setAutoFillBackground(False)
        ExistingAnalysesPanel.setStyleSheet(
            "\n"
            "    QGroupBox{font-weight:600;margin-top:8px;}\n"
            "    QGroupBox::title{subcontrol-origin: margin; left: 6px; padding:2px 4px;}\n"
            "    QLineEdit{border:1px solid #3c3f44;border-radius:6px;padding:6px;}\n"
            "    QLineEdit:focus{border-color:#5865f2;}\n"
            "    QPushButton{border:1px solid #3c3f44;border-radius:8px;padding:6px 12px;}\n"
            "    QPushButton:hover{border-color:#5865f2;}\n"
            "    #okButton { background:rgb(35,144,236); color:white; border:0; border-radius:8px; padding:6px 12px; }\n"
            "    #cancelButton { background:rgb(153,12,25); color:white; border:0; border-radius:8px; padding:6px 12px; }\n"
            "    /* Popup styling */\n"
            "    #collectionsPopupFrame { background:#1b1c20; border:1px solid #3c3f44; border-radius:10px; }\n"
            "    #collectionsPopupHeader { font-weight:600; padding:6px 8px; }\n"
            "    #binariesPopupFrame { background:#1b1c20; border:1px solid #3c3f44; border-radius:10px; }\n"
            "    #binariesPopupHeader { font-weight:600; padding:6px 8px; }\n"
            "   "
        )
        self.rootLayout = QtWidgets.QVBoxLayout(ExistingAnalysesPanel)
        self.rootLayout.setContentsMargins(12, 12, 12, 12)
        self.rootLayout.setSpacing(10)
        self.rootLayout.setObjectName("rootLayout")
        self.header = QtWidgets.QFrame(ExistingAnalysesPanel)
        self.header.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.header.setObjectName("header")
        self.headerLayout = QtWidgets.QHBoxLayout(self.header)
        self.headerLayout.setSpacing(12)
        self.headerLayout.setObjectName("headerLayout")
        self.logoArea = QtWidgets.QLabel(self.header)
        self.logoArea.setMinimumSize(QtCore.QSize(96, 96))
        self.logoArea.setMaximumSize(QtCore.QSize(96, 96))
        self.logoArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.logoArea.setText("")
        self.logoArea.setPixmap(
            QtGui.QPixmap(
                "reai_toolkit/app/components/forms/existing_analysis/../../resources/reveng_ai_logo.jpg"
            )
        )
        self.logoArea.setScaledContents(True)
        self.logoArea.setObjectName("logoArea")
        self.headerLayout.addWidget(self.logoArea)
        self.titleLayout = QtWidgets.QVBoxLayout()
        self.titleLayout.setObjectName("titleLayout")
        self.titleLabel = QtWidgets.QLabel(self.header)
        self.titleLabel.setStyleSheet("font-size:18px;font-weight:600;")
        self.titleLabel.setObjectName("titleLabel")
        self.titleLayout.addWidget(self.titleLabel)
        self.subtitleLabel = QtWidgets.QLabel(self.header)
        self.subtitleLabel.setStyleSheet("color: palette(placeholderText);")
        self.subtitleLabel.setObjectName("subtitleLabel")
        self.titleLayout.addWidget(self.subtitleLabel)
        self.headerLayout.addLayout(self.titleLayout)
        self.rootLayout.addWidget(self.header)
        self.stack = QtWidgets.QStackedWidget(ExistingAnalysesPanel)
        self.stack.setObjectName("stack")
        self.pageSelect = QtWidgets.QWidget()
        self.pageSelect.setObjectName("pageSelect")
        self.pageSelectLayout = QtWidgets.QVBoxLayout(self.pageSelect)
        self.pageSelectLayout.setObjectName("pageSelectLayout")
        self.groupSelect = QtWidgets.QGroupBox(self.pageSelect)
        self.groupSelect.setObjectName("groupSelect")
        self.groupSelectLayout = QtWidgets.QVBoxLayout(self.groupSelect)
        self.groupSelectLayout.setObjectName("groupSelectLayout")
        self.tableAnalyses = QtWidgets.QTableWidget(self.groupSelect)
        self.tableAnalyses.setMinimumSize(QtCore.QSize(550, 0))
        self.tableAnalyses.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableAnalyses.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.AdjustToContents
        )
        self.tableAnalyses.setAlternatingRowColors(True)
        self.tableAnalyses.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableAnalyses.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableAnalyses.setWordWrap(True)
        self.tableAnalyses.setRowCount(0)
        self.tableAnalyses.setColumnCount(4)
        self.tableAnalyses.setObjectName("tableAnalyses")
        item = QtWidgets.QTableWidgetItem()
        self.tableAnalyses.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAnalyses.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAnalyses.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAnalyses.setHorizontalHeaderItem(3, item)
        self.tableAnalyses.horizontalHeader().setVisible(False)
        self.tableAnalyses.horizontalHeader().setCascadingSectionResizes(True)
        self.tableAnalyses.horizontalHeader().setDefaultSectionSize(110)
        self.tableAnalyses.horizontalHeader().setStretchLastSection(False)
        self.tableAnalyses.verticalHeader().setVisible(False)
        self.groupSelectLayout.addWidget(self.tableAnalyses)
        self.pageSelectLayout.addWidget(self.groupSelect)
        self.loadingBar = QtWidgets.QProgressBar(self.pageSelect)
        self.loadingBar.setVisible(False)
        self.loadingBar.setMinimum(0)
        self.loadingBar.setMaximum(0)
        self.loadingBar.setProperty("value", -1)
        self.loadingBar.setTextVisible(True)
        self.loadingBar.setObjectName("loadingBar")
        self.pageSelectLayout.addWidget(self.loadingBar)
        self.buttonsRowSelect = QtWidgets.QHBoxLayout()
        self.buttonsRowSelect.setObjectName("buttonsRowSelect")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.buttonsRowSelect.addItem(spacerItem)
        self.cancelButton = QtWidgets.QPushButton(self.pageSelect)
        self.cancelButton.setObjectName("cancelButton")
        self.buttonsRowSelect.addWidget(self.cancelButton)
        self.okButton = QtWidgets.QPushButton(self.pageSelect)
        self.okButton.setDefault(True)
        self.okButton.setObjectName("okButton")
        self.buttonsRowSelect.addWidget(self.okButton)
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.buttonsRowSelect.addItem(spacerItem1)
        self.pageSelectLayout.addLayout(self.buttonsRowSelect)
        self.stack.addWidget(self.pageSelect)
        self.pageResults = QtWidgets.QWidget()
        self.pageResults.setObjectName("pageResults")
        self.pageResultsLayout = QtWidgets.QVBoxLayout(self.pageResults)
        self.pageResultsLayout.setObjectName("pageResultsLayout")
        self.stack.addWidget(self.pageResults)
        self.rootLayout.addWidget(self.stack)

        self.retranslateUi(ExistingAnalysesPanel)
        self.stack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ExistingAnalysesPanel)

    def retranslateUi(self, ExistingAnalysesPanel):
        _translate = QtCore.QCoreApplication.translate
        ExistingAnalysesPanel.setWindowTitle(
            _translate("ExistingAnalysesPanel", "RevEng.AI — Ann")
        )
        self.titleLabel.setText(
            _translate("ExistingAnalysesPanel", "RevEng.AI — Existing Analyses")
        )
        self.subtitleLabel.setText(
            _translate(
                "ExistingAnalysesPanel", "Select an existing analysis to attach to"
            )
        )
        self.groupSelect.setTitle(
            _translate("ExistingAnalysesPanel", "Analysis Selection")
        )
        self.tableAnalyses.setSortingEnabled(True)
        item = self.tableAnalyses.horizontalHeaderItem(0)
        item.setText(_translate("ExistingAnalysesPanel", "Select"))
        item = self.tableAnalyses.horizontalHeaderItem(1)
        item.setText(_translate("ExistingAnalysesPanel", "Virtual Address"))
        item = self.tableAnalyses.horizontalHeaderItem(2)
        item.setText(_translate("ExistingAnalysesPanel", "Current Name"))
        item = self.tableAnalyses.horizontalHeaderItem(3)
        item.setText(_translate("ExistingAnalysesPanel", "Current Mangled Name"))
        self.loadingBar.setFormat(_translate("ExistingAnalysesPanel", "Processing…"))
        self.cancelButton.setText(_translate("ExistingAnalysesPanel", "Cancel"))
        self.okButton.setText(_translate("ExistingAnalysesPanel", "OK"))
